//@version=2
////////////////////////////////////////////////////////////
//  Copyright by HPotter v1.0 27/06/2018
// The name ‘Floor-Trader Pivot,’ came from the fact that Pivot points can 
// be calculated quickly, on the fly using price data from the previous day 
// as an input. Although time-frames of less than a day can be used, Pivots are 
// commonly plotted on the Daily Chart; using price data from the previous day’s 
// trading activity. 
//
// You can change long to short in the Input Settings
// WARNING:
// - For purpose educate only
// - This script to change bars colors.
////////////////////////////////////////////////////////////
strategy(title="HLC3 Colored Bars Trend_1", shorttitle="HLC3 Colored Bars Trend_1", overlay = true)
xHigh  = security(tickerid,"D", high[1])
xLow   = security(tickerid,"D", low[1])
xClose = security(tickerid,"D", close[1])
reverse = input(false, title="Trade reverse")
multUp =  input(title="Green Multiplier", type=float, defval=1.00, minval=-10.00, maxval=10.00, step=0.001)
multDn =  input(title="Red Multiplier", type=float, defval=1.00, minval=-10.00, maxval=10.00, step=0.001)
vPP = (xHigh+xLow+xClose) / 3
vR1 = multUp * (vPP * 2) - xLow
vS1 = multDn * (vPP * 2) - xHigh
pos = iff(close > vR1, 1,
       iff(close < vS1, -1, nz(pos[1], 0))) 
possig = iff(reverse and pos == 1, -1,
          iff(reverse and pos == -1, 1, pos))	   
if (possig == 1) 
    strategy.entry("Long", strategy.long)
if (possig == -1)
    strategy.entry("Short", strategy.short)	   	    
barcolor(possig == -1 ? red: possig == 1 ? green : blue ) 