// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/

//@version=4
//Indicator by CK(pckalai) - Published

//Trade the steps - This script/indicator is designed with the main purpose of identifying the strength of the instrument. 
//Inputs can be changed by users as per their own rules as per their matching style. 

study(title="Step Rider", shorttitle="CKSR", overlay=true)

isHMA = input(false, title="Use HMA")

//HMA Lines

//HMA Trade Setup

hmaMediumPeriod  = input(100, minval=1, title="HMA Trade Period")
hmaMedium        = hma(input(close), hmaMediumPeriod)
plot(isHMA and hmaMedium ? hmaMedium : na, color=#4B0082, linewidth=2, title="HMA Trade Setup")

//HMA Trend Line

hmaLongPeriod  = input(300, minval=1, title="HMA Trend Period")
hmaLong        = hma(input(close), hmaLongPeriod)
hmaTrendColor = (close > hmaLong) ? color.green : color.red
plot(isHMA and hmaLong ? hmaLong : na, color=hmaTrendColor, linewidth=3, title="HMA Trend Line")

//Donchian 50 - Medium Term

DCLength = input(50, minval=1)
DCLower = lowest(DCLength)
DCUpper = highest(DCLength)
DCBasis = avg(DCUpper, DCLower)

//Donchian 150 - Intermediate Term

DCILength = input(150, minval=1)
DCILower = lowest(DCILength)
DCIUpper = highest(DCILength)
DCIBasis = avg(DCIUpper, DCILower)


//Donchian 300 - Long Term

DCLLength = input(300, minval=1)
DCLLower = lowest(DCLLength)
DCLUpper = highest(DCLLength)
DCLBasis = avg(DCLUpper, DCLLower)


//Donchian 600 - Very Long Term

isVL = input(false, title="Show very long term")
DCVLength = input(600, minval=1)
DCVLower = lowest(DCVLength)
DCVUpper = highest(DCVLength)
DCVBasis = avg(DCVUpper, DCVLower)

plot(isVL and DCVBasis ? DCVBasis : na, "DC Long Basis", color=color.aqua, linewidth=3)

//Donchian 9 - Short Term Stop

isStop = input(false, title="Show Tight Stop")
DCSLength = input(9, minval=1)
DCSLower = lowest(DCSLength)
DCSUpper = highest(DCSLength)
DCSBasis = avg(DCSUpper, DCSLower)

plot((isStop and DCSBasis) ? DCSBasis : na, "DC Stop Basis", color=color.black, linewidth=2)

maColor = (close > DCBasis) ? color.lime : color.red

DCBasisS = plot(DCBasis, "DC Basis", color=maColor, linewidth=2)
DCBasisI = plot(DCIBasis, "DC Intermediate Basis", color=color.fuchsia, linewidth=2)
DCBasisL = plot(DCLBasis, "DC Long Basis", color=color.orange, linewidth=2)

fillColor = (close > DCBasis) ? color.lime : color.red
fillColorI = (close > DCIBasis) ? color.lime : color.red
fillColorL = (close > DCLBasis) ? color.lime : color.red

neutralZonePlot = plot(ohlc4, style=plot.style_circles, linewidth=0, title="Zone Style")
fill(neutralZonePlot, DCBasisS, color=fillColor, transp=95, title="Medium Fill Color")
fill(neutralZonePlot, DCBasisI, color=fillColorI, transp=95, title="Intermediate Fill Color")
fill(neutralZonePlot, DCBasisL, color=fillColorL, transp=95, title="Long Fill Color")

//1 EMA - Long Term

showEMA1 = input(false, title="Exponential Moving Average - Long Term")
emaLongerPeriod = input(200, minval=1, title="EMA Longer Period")
emaLong       = ema(input(close), emaLongerPeriod)
plot(showEMA1 and emaLong ? emaLong : na, color=color.gray, linewidth=2, title="EMA Longer Period")

//Disclaimer: Idea of publishing this script is to identify the strength of the instrument using multiple confirmation. 
//Disclaimer: Using this indicator, changing inputs, and trading decisions are upto the users/traders.
//Courtesy: Thanks to Richard Donchian, Alan Hull as this indicator/script inspired by Donchian Channels, Hull Moving Average