// @version=4
study("Anti-Volume Stop Loss", shorttitle = "AVSL", max_bars_back=5000 ,overlay = true)


lenF = input(12, minval=1, title="Fast average")                                // amount of bars used as sample to calculate fast moving average   
srcF = input(close, title="Fast Price type" )                                   // type of price reading for fast moving average
lenS = input(26, minval=1, title="Slow average")                                // amount of bars used as sample to calculate slow moving average
srcS = input(close, title="Slow Price type" )                                   // type of price reading for slow moving average, 
lenT = input(9, minval=1, title="Signal")                                       // amount of bars used to calculate signal for VPCI
mult = input(2.0, minval=0.001, maxval=50, title="StdDev")
offset = input(2, "Offset", type = input.integer, minval = -500, maxval = 500)

// Functions

PriceFun(VPC,VPR,VM,src) =>                                                     //function calculating stop-loss step in relation with Volume and minimal price
    VPCI=VPC*VPR*VM
    
    lenV = if VPC <0
        int(round(abs(VPCI-3)))
    else if VPC>=0
        round(VPCI+3)
    else
        1
    
    VPCc = if (VPC > -1 and VPC <0)
        -1
    else if (VPC < 1 and VPC >= 0)
        1
    else
        VPC
        
    Price=0.0
    for i=0 to lenV - 1
        Price:=Price+(src[i]*1/VPCc[i]*1/VPR[i])
    PriceV=Price/lenV/100
    max_bars_back(PriceV, 5000)
    PriceV
    
// Caluclations

VWmaS = vwma(srcS,lenS)                                                         // Fast volume weighted moving average
VWmaF = vwma(srcF,lenF)                                                         // Slow volume weighted moving average
AvgS = sma(srcS,lenS)                                                           // Slow Volume average
AvgF = sma(srcF,lenF)                                                           // Fast Volume average
VPC = VWmaS - AvgS                                                              // Volume-Price Confirmation/Contradication VPC+/-
VPR = VWmaF/AvgF                                                                // Volume-Price Ratio
VM = sma(volume,lenF)/sma(volume,lenS)                                          // Volume Multipler
VPCI=VPC*VPR*VM                                                                 // Volume-Price Confiramtion indicator

DeV = mult*VPCI*VM                                                              // Deviation
AVSL = sma(low - PriceFun(VPC,VPR,VM,low) + DeV , lenS)                         

// Plots

plot(AVSL, title="AWSL", color = color.white, transp=0, linewidth=1, style=plot.style_cross, offset=offset)